language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_ABI=armeabi-v7a
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - yes | sdkmanager "platforms;android-27"
scripts:
  - "./gradlew assembleRelease"
